# Generated by Django 5.1.7 on 2025-05-04 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apoteker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('spesialisasi', models.CharField(max_length=50)),
                ('jadwal_praktik', models.CharField(help_text='Masukkan hari praktik, pisahkan dengan koma', max_length=100)),
                ('foto', models.ImageField(blank=True, default='dokter/foto/default.jpg', null=True, upload_to='dokter/foto/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokter.poli')),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10, null=True)),
                ('metode_pembayaran', models.CharField(blank=True, choices=[('Tunai', 'Tunai'), ('Asuransi', 'Asuransi'), ('Kartu Kredit', 'Kartu Kredit')], max_length=50, null=True)),
                ('nama_asuransi', models.CharField(blank=True, max_length=100, null=True)),
                ('nomor_asuransi', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('golongan_darah', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('berat_badan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tinggi_badan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('riwayat_penyakit', models.TextField(blank=True)),
                ('riwayat_alergi', models.TextField(blank=True)),
                ('riwayat_pengobatan', models.TextField(blank=True)),
                ('obat_saat_ini', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Konsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_konsultasi', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Direspons', 'Direspons'), ('Selesai', 'Selesai')], default='Menunggu', max_length=20)),
                ('waktu_aktivitas_terakhir', models.DateTimeField(blank=True, null=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konsultasi', to='dokter.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konsultasi', to='dokter.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='JanjiTemu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Dipanggil', 'Dipanggil'), ('Selesai', 'Selesai')], default='Menunggu', max_length=20)),
                ('keluhan_utama', models.TextField(blank=True, null=True)),
                ('kode_antrian', models.CharField(blank=True, max_length=20, unique=True)),
                ('biaya_konsultasi', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10)),
                ('status_pembayaran', models.CharField(choices=[('Belum Dibayar', 'Belum Dibayar'), ('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Dibayar', 'Dibayar'), ('Gagal', 'Gagal')], default='Belum Dibayar', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokter.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokter.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='PesanKonsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengirim', models.CharField(choices=[('Pasien', 'Pasien'), ('Dokter', 'Dokter')], max_length=20)),
                ('isi', models.TextField()),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
                ('konsultasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan', to='dokter.konsultasi')),
            ],
        ),
        migrations.CreateModel(
            name='RekamMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('diagnosa', models.TextField()),
                ('catatan', models.TextField(blank=True)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokter.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokter.pasien')),
                ('resep', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apoteker.resep')),
            ],
        ),
    ]
