# Generated by Django 5.1.7 on 2025-05-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='janjitemu',
            name='diperiksa_perawat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='janjitemu',
            name='keluhan_utama',
            field=models.TextField(blank=True, default='Tidak ada keluhan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='janjitemu',
            name='status_pembayaran',
            field=models.CharField(choices=[('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Dibayar', 'Dibayar'), ('Gagal', 'Gagal')], default='Menunggu Pembayaran', max_length=50),
        ),
    ]
