# Generated by Django 5.1.7 on 2025-05-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokter', '0002_janjitemu_diperiksa_perawat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perawat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('telepon', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('poli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokter.poli')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PemeriksaanAwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemeriksaan', models.DateTimeField(auto_now_add=True)),
                ('tekanan_darah', models.CharField(blank=True, max_length=10)),
                ('suhu_badan', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('berat_badan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tinggi_badan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('janji_temu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pemeriksaan_awal', to='dokter.janjitemu')),
                ('perawat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perawat.perawat')),
            ],
        ),
    ]
