# Generated by Django 5.1.7 on 2025-05-04 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('stok', models.IntegerField(default=0)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Menunggu', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status_pembayaran', models.CharField(choices=[('Belum Dibayar', 'Belum Dibayar'), ('Sedang Diproses', 'Sedang Diproses'), ('Dibayar', 'Dibayar'), ('Gagal', 'Gagal')], default='Belum Dibayar', max_length=20)),
                ('midtrans_transaction_id', models.CharField(blank=True, help_text='ID transaksi dari Midtrans', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apoteker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nomor_lisensi', models.CharField(max_length=50)),
                ('telepon', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoteker.obat')),
            ],
        ),
        migrations.CreateModel(
            name='PengeluaranObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengeluaran', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('apoteker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoteker.apoteker')),
            ],
        ),
    ]
