# Generated by Django 5.1.7 on 2025-05-04 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apoteker', '0001_initial'),
        ('dokter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='dokter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokter.dokter'),
        ),
        migrations.AddField(
            model_name='resep',
            name='pasien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokter.pasien'),
        ),
        migrations.AddField(
            model_name='pengeluaranobat',
            name='resep',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apoteker.resep'),
        ),
        migrations.AddField(
            model_name='detailresep',
            name='resep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='apoteker.resep'),
        ),
    ]
